config/routes.rb
ManUp::Application.routes.draw do
  root to: 'pages#index'
  
  get "sitemap" => "pages#sitemap", defaults: { format: "xml" }
  
  get "login" => "sessions#new"
  post "login" => "sessions#create"
  delete "logout" => "sessions#destroy"
  
  resources :essays, only: [:show, :index], path: "levnadsrelger"
  resources :resources, path: "resurser"
  
  namespace :admin do
    resources :essays
    resources :resources
  end
  
end

app/models/essay.rb
class Essay < ActiveRecord::Base
  
  scope :published, where(published: true)
  scope :latest, published.order("created_at DESC").limit(3)
  
  validates :body,  presence: true
  validates :slug,  presence: true,
                    uniqueness: true
  validate :should_have_an_ingress
  
  before_validation :create_slug
  
  def title
    return nokogiri_body.css("h1").first.try(:text)
  end
  
  def ingress
    return nokogiri_body.css("p").first.try(:text)
  end
  
  def to_html
    return "" unless body
    RDiscount.new(body).to_html
  end
  
  def to_param
    slug
  end
  
  private
  
    def should_have_an_ingress
      errors.add(:body, "should have an ingress") unless ingress
    end
    
    def create_slug
      self.slug = self.title.try(:parameterize)
    end
    
    def nokogiri_body
      Nokogiri::HTML(to_html)
    end
end

app/models/resource.rb
class Resource < ActiveRecord::Base
  
  scope :podcasts, where(category: "Podcast")
  scope :books, where(category: "Book")
  scope :latest, order("created_at DESC").limit(3)
end

app/controllers/admin/essays_controller.rb
class Admin::EssaysController < ApplicationController
  before_filter :require_admin
  
  def new
    @essay = Essay.new
  end
  
  def edit
    @essay = Essay.find_by_slug(params[:id])
  end
  
  def destroy
    @essay = Essay.find_by_slug(params[:id])
    if @essay.destroy
      redirect_to root_path
    else
      redirect_to @essay
    end
  end
  
  def update
    @essay = Essay.find_by_slug(params[:id])
    if @essay.update_attributes(params[:essay])
      redirect_to @essay
    else
      render :edit
    end
  end
  
  def create
    @essay = Essay.new(params[:essay])
    if @essay.save
      redirect_to @essay
    else
      render :new
    end
  end
end

app/controllers/admin/resources_controller.rb
#coding:UTF-8
class Admin::ResourcesController < ApplicationController
  before_filter :require_admin
  
  def new
    @resource = Resource.new
  end
  
  def create
    if @resource = Resource.create(params[:resource])
      redirect_to resources_path, notice: "Din resurs har lagts till"
    else
      render :new
    end
  end
  
  def edit
    @resource = Resource.find(params[:id])
  end
  
  def update
    @resource = Resource.find(params[:id])
    if @resource.update_attributes(params[:resource])
      redirect_to resources_path, notice: "Resursen är uppdaterad."
    else
      render :update
    end
  end
  
  def destroy
    Resource.find(params[:id]).destroy
    redirect_to resources_path, notice: "Resursen borttagen"
  end
end

app/controllers/application_controller.rb
#coding:utf-8
class ApplicationController < ActionController::Base
  protect_from_forgery
  
  before_filter :ensure_domain
  
  helper_method :admin?
  
  private
  
  def ensure_domain
    redirect_to "http://#{ENV['DOMAIN']}#{request.path}" if ENV['DOMAIN'] && request.host != ENV['DOMAIN']
  end
  
  def admin?
    session[:is_admin]
  end
  
  def require_admin
    redirect_to( login_path, alert: "Du måste logga in!") unless admin?
  end
end

app/controllers/essays_controller.rb
class EssaysController < ApplicationController
  def show
    @essay = Essay.find_by_slug(params[:id])
  end
  
  def index
    @essays = Essay.published
    @essays = Essay.all if admin?
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
    @latest_essays = Essay.latest
    @essay_count = Essay.published.count
    @podcasts_count = Resource.podcasts.count
    @podcasts = Resource.latest.podcasts
    @books_count = Resource.books.count
    @books = Resource.latest.books
  end
  
  def sitemap
    @pages = []
    
    @pages << { url: root_url, changefreq: "daily", priority: 1 }
    @pages << { url: essays_url }
    @pages << { url: resources_url }
    
    Essay.published.each { |essay| @pages << { url: essay_url(essay) } }
    
    respond_to do |format|
      format.xml # sitemap.xml.builder
    end
  end
end

app/controllers/resources_controller.rb
class ResourcesController < ApplicationController
  def index
    @books = Resource.books
    @podcasts = Resource.podcasts
  end
end

app/controllers/sessions_controller.rb
#coding:UTF-8
class SessionsController < ApplicationController
  
  def create
    if params[:login][:username] == ENV["admin_user"] && params[:login][:password] == ENV["admin_password"]
      session[:is_admin] = true
      redirect_to root_path, notice: "Du är nu inloggad som admin."
    else
      flash.now.alert = "Felaktiga uppgifter angivna."
      render :new
    end
  end
  
  def destroy
    session[:is_admin] = nil
    redirect_to root_path, notice: "Du har nu blivit utloggad"
  end
end

app/helpers/admin/essays_helper.rb
module Admin::EssaysHelper
end

app/helpers/admin/resources_helper.rb
module Admin::ResourcesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
  
  def set_title(title)
    content_for :title do
      title
    end
  end
  
  def set_description(description)
    content_for :description do
      description
    end
  end
end

app/helpers/essays_helper.rb
module EssaysHelper
  def row_it(essays, number_of_rows = 3)
    
    html = ""
    
    essays.each_with_index do |essay, index|
      html << '<div class="row">' if (index % number_of_rows) == 0
      html << yield(essay)
      html << '</div>' if (index % number_of_rows) == (number_of_rows - 1)
    end
  end
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/resources_helper.rb
module ResourcesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/views/admin/essays/edit.html.slim
.row
  h1 Ändra artikeln

  = form_for @essay, url: admin_essay_path(@essay) do |f|
    = f.label :body
    = f.text_area :body
    = f.label :published, "Public"
    = f.check_box :published
    = f.submit "Update"

app/views/admin/essays/new.html.slim
.row
  h1 Lägg till en artikel
  
  = form_for @essay, url: admin_essays_path do |f|
    = f.label :body
    = f.text_area :body
    = f.label :published, "Public"
    = f.check_box :published
    = f.submit "Add"

app/views/admin/resources/edit.html.slim
.row
  h1 Ändra resursen
  
  = form_for @resource, url: admin_resource_path(@resource) do |f|
    = f.label :title, "Titel"
    = f.text_field :title
    = f.label :description, "Beskrivning"
    = f.text_area :description
    = f.label :url
    = f.text_field :url
    = f.label :category, "Kategori"
    = f.select :category, [["Podcast", "Podcast"], ["Bok", "Book"]]
    = f.submit "Uppdatera"

app/views/admin/resources/new.html.slim
.row
  h1 Lägg till en resurs
  
  = form_for @resource, url: admin_resources_path do |f|
    = f.label :title, "Titel"
    = f.text_field :title
    = f.label :description, "Beskrivning"
    = f.text_area :description
    = f.label :url
    = f.text_field :url
    = f.label :category, "Kategori"
    = f.select :category, [["Podcast", "Podcast"], ["Bok", "Book"]]
    = f.submit "Lägg till"

app/views/essays/_essays_grid_3.html.slim
- essay = essays_grid_3
- essay_counter = essays_grid_3_counter
- last = (essay_counter + 1) == total
- essay_count_mod_3 = (essay_counter % 3)

== '<div class="row">' if essay_count_mod_3 == 0
article.essay-front-page.four.columns class="#{"unpublished" unless essay.published? }"
  header
    h1 = link_to essay.title, essay_path(essay)
  p = essay.ingress
== "</div>" if last || essay_count_mod_3 == 2

app/views/essays/index.html.slim
section
  == render partial: "essays_grid_3", collection: @essays, locals: {total: @essays.count }

app/views/essays/show.html.slim
- set_title @essay.title

article#essay-full.row
  - if admin?
    nav
      ul
        li.admin-item = link_to "Edit", edit_admin_essay_path(@essay)
        li.admin-item = link_to "Delete", admin_essay_path(@essay), method: :delete
  == @essay.to_html.gsub(@essay.ingress, "<b>#{@essay.ingress}</b>")

app/views/layouts/application.html.slim
doctype 5
html lang="sv"
  head
    title = content_for?(:title) ? yield(:title) : "ManUp!"
    meta charset="UTF-8"
    - if content_for?(:description)
      meta name="description" content="#{yield :description}"
    = stylesheet_link_tag    "application", :media => "all"
    = javascript_include_tag "application"
    link rel="sitemap" type="application/xml" title="Sitemap" href="/sitemap"
    = csrf_meta_tags
    == render(partial: "shared/ga") if Rails.env.production? 

  body
    #menu-container.container
      header.row
        nav
          ul
            li = link_to "Hem", root_path
            li = link_to "Artiklar", essays_path
            li = link_to "Resurser", resources_path
            - if admin?
              li.admin-item = link_to "Skapa en essay", new_admin_essay_path
              li.admin-item = link_to "Lägg till resurs", new_admin_resource_path
              li.admin-item = link_to "Logga ut", logout_path, method: :delete
    
    #main-container.container
      - if flash.notice
        .row.alert-box
          = flash.notice
          a.close &times;
          
      - if flash.alert
        .row.alert-box.error
          = flash.alert
          a.close &times;
      
      = yield
      
      footer.row
        ' Detta är en totally awesome footer!

app/views/pages/index.html.slim
.row
  header#main.four.columns
    h1.cursive manup.se
    p Detta är en text som egentligen inte säger så himla mycket, men den behöver vara några rader.
  .eight.columns
    p 
      span#essay-count = @essay_count
      |  levnadsregler
    p 
      span#podcast-count = @podcasts_count
      |  podcasts
    p 
      span#book-count = @books_count
      |  böcker

section
  header.row
    h1 Nya artiklar
  
  .row
    - @latest_essays.each do |essay|
      article.essay-front-page.four.columns
        header
          h1 = link_to essay.title, essay_path(essay)
        p = essay.ingress

section
  header.row
    h1 Senaste resurserna
  
  .row
    #latest-podcasts.six.columns
      h2 Podcasts
      ul
        - @podcasts.each do |podcast|
          li = podcast.title
      
    #latest-books.six.columns
      h2 Böcker
      ul
        - @books.each do |book|
          li = book.title

app/views/resources/index.html.slim
section
  header.row
    h1 Resurser
    p Lite snick-snack om resureserna

  section#podcasts.row
    header
      h1.row Podcasts
    - @podcasts.each do |podcast|
      article.row
        header
          h1 = link_to podcast.title, podcast.url
        p = podcast.description
        - if admin?
          =' link_to("Ändra", edit_admin_resource_path(podcast))
          =' link_to("Ta bort", admin_resource_path(podcast), method: :delete)

  section#books.row
    header
      h1.row Böcker
    - @books.each do |book|
      article.row
        header
          h1 = link_to book.title, book.url
        p = book.description
        - if admin?
          =' link_to("Ändra", edit_admin_resource_path(book))
          =' link_to("Ta bort", admin_resource_path(book), method: :delete)